### PR TITLE
Working template

### PR DESCRIPTION
**Pull request by Quentin-Macquart**
Hey guys! 
just add the Eye and its animation, the Slider for the HP with Api call!

### CODE REVIEW

**Review by BBriset — DISMISSED** [review]
Seems good to me

**Comment by LoicBrassart** [comment]
No SM validation

**Comment by BBriset** [comment]
Quentin was the sm, So i validate it as Po last week

**Comment by LoicBrassart** [comment]
Still no validation :p 
(And you should be 100% focused on @Hacene010 's lesson about MySQL right now :smirk: )

**Review by BBriset — APPROVED** [review]

**Comment by BBriset** [comment]
i found the approval button... sorry for the wast of time..

**Review by Hacene010 — APPROVED** [review]
Seems ok for me

**Pull request merged**
